preload = [ "../core/bun-plugin-yml/src/index.ts" ]

[install]
# set default registry as a string
registry = { url = "https://registry.npmjs.org" }

# where `bun install --global` installs packages
globalDir = "~/.stacks/bun/install/global"

# where globally-installed package bins are linked
globalBinDir = "~/.stacks/bin"

# whether to install optionalDependencies (currently needed because all drivers are optional)
optional = true

# whether to install devDependencies
dev = true

# whether to install peerDependencies
peer = true

# equivalent to `--production` flag
production = false

# equivalent to `--frozen-lockfile` flag
frozenLockfile = false

# equivalent to `--dry-run` flag
dryRun = false

[install.cache]
# the directory to use for the cache
dir = "~/.stacks/install/cache"

# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
disable = false

# when true, always resolve the latest versions from the registry
disableManifest = false

[install.lockfile]

# path to read bun.lockb from
path = "bun.lockb"

# path to save bun.lockb to
savePath = "bun.lockb"

# whether to save the lockfile to disk
save = true
